%YAML 1.2
---
name: 'kb1-64x6'                       # ideally no spaces
gpu: 0                                 # gpu id to process on

dataset: 
  num_chunks: 5000                   # newest nof chunks to parse
  train_ratio: 0.90                    # trainingset ratio
  # For separated test and train data.
  # input_train: 'games/*' # supports glob
  # input_test: 'games/*'  # supports glob
  # For a one-shot run with all data in one directory.
  input: 'games/'

training:
    batch_size: 256                   # training batch
    test_steps: 2000                   # eval test set values after this many steps
    train_avg_report_steps: 200        # training reports its average values after this many steps.
    total_steps: 140000                # terminate after these steps
    # checkpoint_steps: 10000          # optional frequency for checkpointing before finish
    shuffle_size: 524288               # size of the shuffle buffer
    lr_values:                         # list of learning rates
        - 0.5
        - 0.05
        - 0.005
        - 0.0005
    lr_boundaries:                     # list of boundaries
        - 5000
        - 30000
        - 100000
    policy_loss_weight: 1.0            # weight of policy loss
    value_loss_weight: 1.0             # weight of value loss
    path: '/path/to/store/networks'    # network storage dir

model:
  filters: 32
  residual_blocks: 4
  bottleneck: 32
  multiple_conv: False
  preact: False
...
